### ISSUE TITLE
First UV set in USD is named "st"

### ISSUE THREAD

**Issue by JGamache-autodesk** [pablode/guc#22]
Small but important fix in [makeStSetName()](https://github.com/pablode/guc/blob/main/src/libguc/src/naming.cpp#L58). The index should only be appended if the index is > 0.

**Comment by pablode** [comment]
Hi! Afaik 'st' is a convention and there's no guarantee that the implementation will use it. This is why I always emit explicit `UsdPrimvarReader_float2` and `geompropvalue` nodes. I can understand that some applications do not support these - did you experience any particular issue?

**Comment by JGamache-autodesk** [comment]
Indeed "st. st1, st2" is but one convention. ArKit uses another (uv0, uv1, uv2). Using UsdPrimvarReader and geompropvalue is indeed the right way to handle that so I will close the issue.
