### ISSUE TITLE
more detailed build instructions

### ISSUE THREAD

**Issue by CraigLaMorte** [pablode/guc#25]
Do you happen to have more detailed instructions on how to build this for someone who has never used cmake?  Unsure how to build it after cloning the repository.

**Comment by pablode** [comment]
Hi! Did you check out the [build instructions](https://github.com/pablode/guc#build) in the README?

It seems like you need to build USD with the `--openimageio` flag.

Alternatively, you can try out these prebuilt USD binaries (make sure your Python version matches): https://github.com/pablode/USD/releases/tag/v23.08-ci-release

**Comment by CraigLaMorte** [comment]
ohh thank you, that was it.  Didn't realize i had to check that flag on when building USD.  I was able to build guc successfully now thanks.
